name: expressions and contexts wf
on: workflow_dispatch

jobs:
    expressions-job:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo ${{ 1 }}
                echo ${{ 'testststs' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1>2 }}
                echo ${{ 'string'=='String' }}
                echo ${{ true && false }}
                echo ${{ true || false }}





