name: expressions and contexts wf
on: [push]
run-name: "My test"

jobs:
    expressions-job:
        runs-on: ubuntu-latest
        steps:

            - name: Expressions
              id: expression
              run: |
                echo ${{ 1 }}
                echo ${{ 'testststs' }}
                echo ${{ null }}
                echo ${{ true }}
                echo ${{ 1>2 }}
                echo ${{ 'string'=='String' }}
                echo ${{ true && false }}
                echo ${{ true || false }}
            
            - name: Dummy Step
              id: dummy_step
              run: echo 
              
            - name: Contexts
              run: |
                echo ${{ toJson(github) }}
                echo ${{ toJson(steps) }}
                echo ${{ toJson(job) }}
                echo ${{ toJson(runner) }}
                echo ${{ toJson(secrets) }}









