name: filtering wf
on:
    push:
        branches:
            - main
            - "feature/*"

jobs:
    checkout-test-job:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - name: checkout
              uses: actions/checkout@v4
            - name: list files after
              run: ls -a 
