name: First Workflow test
on: [push]

jobs: 
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello World
        run: echo "Test from othman !!!"
      - name: Multiline command test
        run: |
          node -v
          npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
      - name: View SW Version
        run: sw_vers
  dependant-job: 
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: Write-Output "test independant Job"
      - name: Error Step
        run: xcxvx