name: manually triggered workflow
on: 
    workflow_dispatch:
        inputs:
            inp1:
                description: inp1_desc
                type: string
                required: true
                default: "test_input_value"

jobs:
    log-info:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_REF
                echo $GITHUB_SHA
