name: Status check Workflow
on: push

jobs:
    job-1:
        runs-on: ubuntu-latest
        steps:
            - name: step-0
              run: echo "this step succeed!"
            - name: step-1
              run: exit 1
            - name: step-2
              run: exit 1
            - name: Run Only on failure
              if: failure() && steps.step-1.outcome == 'failure'
              run: echo "step1 failed"
        

    job-2:
        runs-on: ubuntu-latest
        if: failure()
        steps:
            - run: echo "job2"