name: Workflow Dirs & Shells
on: [push]
defaults:
    run:
        shell:  bash


jobs:
    display-wd-info:
        runs-on: ubuntu-latest
        steps:
            - name : Display Working Directory and List Files Windows Ubuntu
              run: |
                pwd
                ls -a
                echo "::error:: My error"
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE

            - name: Change working dir
              working-directory: /home/runner
              run: pwd

    display-wd-info-windows:
        runs-on: windows-latest
        defaults:
            run:
                shell:  pwsh
        steps:
            - name: Display Working Directory and List Files Windows
              shell: bash
              run: |
                pwd
                ls -a
                echo "::error:: My error"
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE
